### ISSUE TITLE
Error: gyroscope calibration failed: no data points

### ISSUE THREAD

**Issue by SahanGura** [pcdangio/ros-driver_mpu9250#10]
I was using mpu-9250 imu to get raw data using this ros driver. This ros driver works fine most of the time but sometimes I get this error when I am trying to run the relevant ros node. Could not figure out why this happens sometimes

**Comment by pcdangio** [comment]
This node assumes that the gyroscope is powered on and sending data when it is first started. At startup, the node attempts to calibrate the gyro, so it waits for 500ms to collect data from the gyroscope to average out the bias. If less than 5 points are collected (meaning the gyro is likely not powered on or sending data), then the node fails and throws this error.

https://github.com/pcdangio/ros-driver_mpu9250/blob/e393907effec9d7ab5e53cdc27ab004f3f7e1d93/src/ros_node.cpp#L112-L117

**Comment by SahanGura** [comment]
Thank you for your explanation. I tried increasing the time period it waits to collect gyroscope data. But still it gives 0 data points. But when I use a python file to read gyroscope data from the imu, I can see gyroscope gives data without an issue. It seems this is a problem with the ros driver and still trying to figure this out.

**Comment by SahanGura** [comment]
I could resolve this issue. That was not an issue of the driver. I changed the connection between interrupt pin and and GPIO pin of rpy, then it started working. During this waiting period interrupt had not been called properly because of that connection issue I guess.

**Comment by pcdangio** [comment]
Great, glad its all working for you now.

Thanks for coming back and closing the issue out!
