### ISSUE TITLE
Can I get covariance values for the sensors using this ros driver?

### ISSUE THREAD

**Issue by SahanGura** [pcdangio/ros-driver_mpu9250#11]
I need to get the sensor covariance of accelerometer, gyroscope and the magnetometer from the imu itself. Can I get those from this driver? If not, how can I get these values?

**Comment by pcdangio** [comment]
I recommend using my [noise_analysis tool](https://github.com/pcdangio/ros-noise_analysis) to measure variances/covariances for the sensors.

FYI, getting sensor covariances is more of an art than a science.

This driver does not do any sort of covariance calculations in real time. The only IMUs that provide this data in real time are the more sophisticated/expensive ones that are running sensor fusion filters/algorithms onboard.
