### ISSUE TITLE
How to use this package with Jetson Nano

### ISSUE THREAD

**Issue by KamalanathanN** [pcdangio/ros-driver_mpu9250#12]
Hi,
Can you please share the changes to make in the base driver class for jetson nano GPIO compatibility.

**Comment by pcdangio** [comment]
The way this package is designed, you shouldn't have to modify any code to implement it on another device such as the nano. This package comes with a base driver class, so all you need to do is extend that class for the particular host device, which is the nano in your case. You can take a look at the rpi_driver class, which is an extension of the base driver class for a raspberry pi.

Unfortunately, I do not have a nano lying around to write the driver extension myself.

If you are able to build one, please do feel free to submit a pull request. I'd be happy to include it in the package.

**Comment by SahanGura** [comment]
@pcdangio I also need to configure this package with jetson nano. Can you give here some guidance to extend the driver for the jetson nano?
