### ISSUE TITLE
There's no data published

### ISSUE THREAD

**Issue by sskorol** [pcdangio/ros-driver_mpu9250#14]
Hi @pcdangio,

I'm trying to get data from [10 DOF IMU Sensor](https://www.waveshare.com/product/10-DOF-IMU-Sensor-C.htm) using your driver. Everything is set up.  A node is started.

![Screenshot from 2022-08-28 03-00-11](https://user-images.githubusercontent.com/6638780/187051954-7cc30286-192d-479a-b11b-2cf71a289427.png)

However, there is no data published on the existing topics:
![Screenshot from 2022-08-28 03-01-18](https://user-images.githubusercontent.com/6638780/187052014-8593aaa6-8798-4a35-9ab2-08c1e31f674a.png)

Do you have any idea what might be the root cause?

Ubuntu 20.04, ROS Noetic, RPi4 B 4Gb

![sensor](https://user-images.githubusercontent.com/6638780/187052183-f1d07941-4895-4214-aba1-7bf7182a13e0.jpg)

![Screenshot from 2022-08-28 03-13-08](https://user-images.githubusercontent.com/6638780/187052228-05fee39f-fd4e-4f1c-91e8-6a931e708a04.png)

**Comment by pcdangio** [comment]
My initial guess is that there is an incorrect interrupt pin assignment. The driver monitors the interrupt pin, which kicks off the process for reading data from the device and publishing it via ROS. Double check that you are setting the ```interrupt_gpio_pin``` parameter properly, including making sure that the correct [Broadcom GPIO pin number](https://pinout.xyz/) is used. By default, the driver uses GPIO 0.
