### ISSUE TITLE
error: set mode for interrupt pin not permitted

### ISSUE THREAD

**Issue by Desoky01** [pcdangio/ros-driver_mpu9250#5]
```
[FATAL] [1598722291.909609022]: initialize: Set mode for interrupt pin not permitted.
[FATAL] [1598722291.933906503]: write_register: I2C write failed.
```

**Comment by imoted** [comment]
The same error happened. It looks the ROS node can connect to pigpiod but, cannot set_mode.

**Comment by pcdangio** [comment]
If you are getting a `initialize: Set mode for interrupt pin not permitted`, it's because your user account on the RPi does not have the right permissions to access the GPIO.

To fix this, you have to either:
- Be a root user
- Add your username to the `gpio` group with `sudo adduser your_username_here gpio` and logging out/in.

**Comment by imoted** [comment]
Thank you. I'd like to add the user to gpio group.

ubuntu@ubuntu:~$ sudo adduser ubuntu gpio
ubuntu@ubuntu:~$ ls -l /dev/gpiomem
crw-rw---- 1 root gpio 244, 0  2月 11  2016 /dev/gpiomem

It looks still the user cannot access to the gpio interrupt.

**Comment by pcdangio** [comment]
Did you log out and log back in after the `adduser` call? That's a necessary step.

`ls -l` shows the groups that have access to the device, but doesn't confirm that your username is part of that group.

Use `groups your_username_here` to verify that your username is in the group.

Let me know how it goes.

**Comment by bjajoh** [comment]
Same issue for me, does anyone know the answer?
Adding "gpio" to the pi user group did not help anything.

**Comment by imoted** [comment]
I did log out / in after the `adduser` call.

And the usergroupe is as follows.

`ubuntu@ubuntu:~$ groups ubuntu
ubuntu : ubuntu adm dialout cdrom floppy sudo audio dip video plugdev netdev lxd i2c gpio
`

Thank you for your support, @pcdangio .

**Comment by pcdangio** [comment]
**I think I may have found the issue:** have you guys [enabled I2C in raspiconfig](https://learn.adafruit.com/adafruits-raspberry-pi-lesson-4-gpio-setup/configuring-i2c)?

Here's my thought trail:

The error you are all seeing is coming from this block (particularly lines 58-61):

https://github.com/pcdangio/ros-driver_mpu9250/blob/4a319442b187331c1ce829621f2e03fdc67c982e/driver_mpu9250/src/rpi_driver.cpp#L42-L69

The raspberry pi driver of this package uses [pigpio](http://abyz.me.uk/rpi/pigpio/index.html) as the interface to the PI's I2C lines. I did some searching in the pigpio source code to see why `set_mode()` would return `PI_NOT_PERMITTED`, and found this:

https://github.com/joan2937/pigpio/blob/cc17196c7586c3625ac8adf8f34838d320ffeda6/pigpio.c#L1945-L1971

This alludes to the case where I2C may not have been enabled on the Pi.  It also shows that if the user is not added in the `gpio` group, you would instead have gotten a `PI_BAD_USER`. So my mistake on the initial incorrect guidance about the user group.

**Comment by bjajoh** [comment]
Thanks for you research but that's not it, sadly. I can see it with the
i2c-tools. Also read it out with a script. It is the pigpio which causes
the problem and I'm not sure why.

Am Mi., 11. Nov. 2020 um 16:30 Uhr schrieb pcdangio <
notifications@github.com>:

**Comment by pcdangio** [comment]
What pin number are you passing to the `interrupt_gpio_pin` parameter in ROS? Further investigation shows that if you pass an invalid pin number, you will receive a `PI_NOT_PERMITTED` from `set_mode()`.

You need to use GPIO numbers instead of actual pin numbers, [which are documented here](http://abyz.me.uk/rpi/pigpio/index.html#Type_3). I guess this is a nuance of using pigpio.

I'm going to update the README documentation to point this out.  Let me know if that fixed it for you.

**Comment by imoted** [comment]
Thanks for you research. 

In my case, I can communicate with I2c devide (MPU6050) by the python smbus lib from ros enviroment on Ubuntu16.04. (https://github.com/FaBoPlatform/FaBo9AXIS-MPU9250-Python)
So I2C should be enabled.

I use the pin8 (GPIO14) and pin3 (SDA) and pin5 (SCL) on raspberry pi.
And I tried the following command from CUI and it works. so GPIO also should be enabled.
```
ubuntu@ubuntu:src [master]$ pigs w 14 1
```

But sadly it looks I don't have the permission to access gpio and i2c from the your ros node.

**Comment by pcdangio** [comment]
Alright just to check the following:
- you are setting the `~/interrupt_gpio_pin` parameter in ROS to 14
- you have called `sudo pigpiod` before running the node

And you still get the permissions error?

If so, can you modify your copy of rpi_driver.cpp to print `interrupt_gpio_pin`  to console right before line 43? That way you can just double check that the right GPIO number is getting passed in.

**Comment by imoted** [comment]
yes I still have the permission error.

`
ubuntu@ubuntu:src$ sudo pigpiod
ubuntu@ubuntu:src$ roslaunch driver_mpu9250 mpu9250.launch 
... logging to /home/ubuntu/.ros/log/03678b1c-27de-11eb-aa5d-b827eb65b193/roslaunch-ubuntu-9179.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:33205/

SUMMARY
========

PARAMETERS
 * /accel_dlpf_frequency: 0
 * /accel_fsr: 0
 * /gyro_dlpf_frequency: 0
 * /gyro_fsr: 0
 * /i2c_address: 0x68
 * /i2c_bus: 1
 * /interrupt_gpio_pin: 14
 * /max_data_rate: 8000
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    driver_mpu9250 (driver_mpu9250/driver_mpu9250_rpi)

auto-starting new master
process[master]: started with pid [9192]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 03678b1c-27de-11eb-aa5d-b827eb65b193
process[rosout-1]: started with pid [9205]
started core service [/rosout]
process[driver_mpu9250-2]: started with pid [9208]
[FATAL] [1605512010.357909968]: initialize: Set mode for interrupt pin not permitted.
[FATAL] [1605512010.358770745]: write_register: I2C write failed.
[driver_mpu9250-2] process has finished cleanly
`


```
<?xml version="1.0"?>
<launch>
    <param name="i2c_bus" value="1"/>
    <param name="i2c_address" value="0x68"/>
    <!-- raspberrypi RX is GPI14 -->
    <param name="interrupt_gpio_pin" value="14"/>
    <!-- 250Hz -->
    <param name="gyro_dlpf_frequency" value="0"/>
    <!-- 460Hz -->
    <param name="accel_dlpf_frequency" value="0"/>
    <!-- +/- 250deg/sec -->
    <param name="gyro_fsr" value="0"/>
    <!-- +/- 2g -->
    <param name="accel_fsr" value="0"/>
    <!--   The maximum allowable sensor data rate, in Hz. 
    Data rate is normally calculated as half of the accel/gyro DLPF frequency (nyquist criterion). 
    This parameter allows maximum cap on the data rate, regardless of the DLPF frequency. -->
    <param name="max_data_rate" value="8000"/>
    <node pkg="driver_mpu9250" type="driver_mpu9250_rpi" name="driver_mpu9250">
    </node>
</launch>
```

**Comment by pcdangio** [comment]
It looks like setting the interrupt_gpio_pin parameter to 14 has solved the interrupt pin initialization problem... you are no longer getting the `initialize: Set mode for interrupt pin not permitted` error.

However, you have a different problem now: you instead received a `MPU9250 device ID mismatch` error. At this point, you are successfully communicating with the device through I2C, however the device itself is indicating its not an MPU9250. Here is the code snippet causing the error:

https://github.com/pcdangio/ros-driver_mpu9250/blob/41e2163cd26d086d6fff8f7d4aa749391cdd39ae/driver_mpu9250/src/driver.cpp#L34-L37

This snippet reads the `WHO_AM_I` register from the MPU9250. This register should always return 0x71 if the device is an MPU9250.  In this case, your device is returning something besides 0x71, indicating it is not an MPU9250. Are you perhaps using a different MPU device, such as the MPU6500?

To debug, you can modify that snippet of code to print out the value read from the register with ROS_INFO_STREAM. Let me know what value you receive from that register.

**Comment by imoted** [comment]
I'm sorry. I didn't realize that the interrupt pin issue was resolved.

As you can imagine, I use the MPU6050, so I changed the ID of "who am I" and comment out the reading part of the magnetometer. and eventually I can get it to work.

Thank you very much.

**Comment by pcdangio** [comment]
No worries at all, glad its all working for you!

**Comment by pcdangio** [comment]
Closing issue: Fixed README documentation so users know that GPIO numbers must be used instead of pin numbers.
